sudo: false
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
env:
- DJANGO="django>=1.8.0,<1.9.0"
- DJANGO="django>=1.9.0,<1.10.0"
- DJANGO="django>=1.10.1,<1.11.0"
- DJANGO="django>=1.11.0,<1.12.0"
script:
  - python setup.py test
